set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_SYSROOT /home/bob/hdd/tegra-cross)

set(LINARO_DIR /home/bob/hdd/tegra-cross/gcc-linaro-5.4.1-2017.05-x86_64_aarch64-linux-gnu/bin)
set(LINARO_PREFIX aarch64-linux-gnu-)
set(CMAKE_C_COMPILER ${LINARO_DIR}/${LINARO_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${LINARO_DIR}/${LINARO_PREFIX}g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
